// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.16 public/assets/_airplane.glb 
// */

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from 'react-three-fiber'
import * as THREE from 'three'

const HELIX_SPEED = 6

export function Airplane(props) {
  const { nodes, materials } = useGLTF('/assets/_airplane.glb')
  const helix = useRef()
  const [target, setTarget] = useState({x:0, y:0})
  const {camera} = useThree()

  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED;
  })

  return (
    <group {...props} dispose={null}>
      <mesh
      geometry={nodes.PUSHILIN_Plane_Circle000.geometry} 
      material={materials.plane} 
      />
      <mesh
      ref = {helix}
      geometry={nodes.PUSHILIN_Plane_Circle001.geometry} 
      material={materials.plane}
      />
    </group>
  )
}

// useGLTF.preload('/assets/_airplane.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/paper_airplane.glb 
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Airplane(props) {
//   const { nodes, materials } = useGLTF('/assets/paper_airplane.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh geometry={nodes.Plane.geometry} material={materials.White} />
//     </group>
//   )
// }

// useGLTF.preload('/assets/paper_airplane.glb')
