/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/_airplane02.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

const HELIX_SPEED = 6

export function Airplane02(props) {
  const { nodes, materials } = useGLTF('/assets/_airplane02.glb')
  const helix = useRef()

  useFrame((_state, delta) => {
    helix.current.rotation.x += delta * HELIX_SPEED;
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} />
      <mesh ref = {helix} geometry={nodes.PUSHILIN_Plane_Circle001.geometry} material={materials.plane} rotation={[-Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/assets/_airplane02.glb')
