/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/_cloud.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber';

export function Cloud(color, props) {
  const { nodes, materials } = useGLTF('/assets/_cloud.glb')

  materials.lambert2SG.color.set("purple");

  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.Node.geometry} 
      material={materials.lambert2SG} 
      position = {[-2,-1,-2]}
      />
      
    </group>
  )
}

useGLTF.preload('/assets/_cloud.glb')
