/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Seven.wong (https://sketchfab.com/Seven.wong)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kiwi-actinide-chinensis-bubble-496fa20f5607461b8f0151c34a519760
Title: Kiwi Actinide Chinensis Bubble
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Triangle } from "./Triangle";

export function BubbleLeft(props) {
  const { nodes, materials } = useGLTF("/assets/bubble/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <Triangle rotation={[0, 0, 0]} />
      <mesh
        geometry={nodes.bubble1_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

export function BubbleRight(props) {
  const { nodes, materials } = useGLTF("/assets/bubble/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <Triangle rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes.bubble1_lambert1_0.geometry}
        material={materials.lambert1}
      />
    </group>
  );
}

useGLTF.preload("/assets/bubble/scene.gltf");
