/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Ju Designer (https://sketchfab.com/JuDesigner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hogwarts-3d-70dcec840f8444dda2974aa6a9b049e2
Title: Hogwarts 3D
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Hogwarts(props) {
  const { nodes, materials } = useGLTF("assets/hogwarts_3d/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.321, 2.425, -0.601]} scale={0.349}>
        <mesh
          geometry={nodes.Object_150.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_151.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.045, 3.739, 0.001]}
        rotation={[0, -1.136, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_201.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_202.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.034, 3.668, 0.024]}
        rotation={[0, -1.136, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_204.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_205.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.007, 3.395, 0.122]}
        rotation={[0, -1.136, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_207.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_208.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.004, 3.324, 0.145]}
        rotation={[0, -1.136, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_210.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_211.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.071, 3.697, -0.181]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_213.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_214.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.068, 3.622, -0.209]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_216.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_217.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.066, 3.546, -0.236]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_219.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_220.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.063, 3.47, -0.265]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_222.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_223.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.061, 3.395, -0.292]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_225.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_226.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.058, 3.324, -0.317]}
        rotation={[0, 1.478, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_228.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_229.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.02, 3.697, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_231.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_232.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.049, 3.622, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_234.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_235.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.075, 3.546, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_237.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_238.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.105, 3.47, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_240.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_241.geometry}
          material={materials.material_0}
        />
      </group>
      <group
        position={[0.132, 3.395, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_243.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_244.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.157, 3.324, -0.077]}
        rotation={[0, 0, -1.553]}
        scale={[0.032, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_246.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_247.geometry}
          material={materials.material}
        />
      </group>
      <group position={[0.014, 1.733, -0.021]} scale={1.326}>
        <mesh
          geometry={nodes.Object_249.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_250.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_251.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_252.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_253.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_254.geometry}
          material={materials.JANELAS}
        />
      </group>
      <group
        position={[0.2, 2.428, 0.406]}
        rotation={[0.012, 0.34, -1.555]}
        scale={0.04}
      >
        <mesh
          geometry={nodes.Object_256.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Object_257.geometry}
          material={materials["Material.016"]}
        />
      </group>
      <group position={[-0.082, 2.233, -0.079]} scale={0.254}>
        <mesh
          geometry={nodes.Object_259.geometry}
          material={materials["JANELAS.001"]}
        />
        <mesh
          geometry={nodes.Object_260.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_261.geometry}
          material={materials.VIDROS}
        />
        <mesh
          geometry={nodes.Object_262.geometry}
          material={materials["LUZ.001"]}
        />
      </group>
      <group position={[-0.085, 2.216, -0.081]} scale={[0.24, 0.335, 0.24]}>
        <mesh
          geometry={nodes.Object_264.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_265.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.145, 2.187, 0.598]}
        rotation={[0, 0.322, 0]}
        scale={0.207}
      >
        <mesh
          geometry={nodes.Object_269.geometry}
          material={materials["JANELAS.001"]}
        />
        <mesh
          geometry={nodes.Object_270.geometry}
          material={materials["LUZ.001"]}
        />
        <mesh
          geometry={nodes.Object_271.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_272.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_273.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <group
        position={[1.262, 2.705, -0.927]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_279.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_280.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[1.135, 2.705, -0.891]}
        rotation={[-Math.PI, -1.318, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_282.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_283.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[1.298, 2.705, -1.059]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_285.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_286.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[1.038, 2.705, -0.984]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_288.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_289.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[1.135, 2.705, -1.151]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_291.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_292.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group position={[-0.855, 2.216, -0.081]} scale={[0.24, 0.335, 0.24]}>
        <mesh
          geometry={nodes.Object_294.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_295.geometry}
          material={materials.VIDROS}
        />
        <mesh
          geometry={nodes.Object_296.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.493, 2.705, -0.927]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_302.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_303.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.366, 2.705, -0.891]}
        rotation={[-Math.PI, -1.318, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_305.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_306.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.529, 2.705, -1.059]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_308.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_309.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[0.269, 2.705, -0.984]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_311.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_312.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.366, 2.705, -1.151]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_314.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_315.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.05, 3.666, 0.09]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.006, 0.037, 0.003]}
      >
        <mesh
          geometry={nodes.Object_321.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_322.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.075, 3.666, 0.097]}
        rotation={[-Math.PI, -1.318, 1.589]}
        scale={[0.006, 0.036, 0.003]}
      >
        <mesh
          geometry={nodes.Object_324.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_325.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.043, 3.666, 0.065]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.006, 0.036, 0.003]}
      >
        <mesh
          geometry={nodes.Object_327.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_328.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.093, 3.666, 0.079]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.006, 0.036, 0.003]}
      >
        <mesh
          geometry={nodes.Object_330.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_331.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.075, 3.666, 0.047]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.006, 0.036, 0.003]}
      >
        <mesh
          geometry={nodes.Object_333.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_334.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.053, 3.717, 0.12]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.005, 0.031, 0.002]}
      >
        <mesh
          geometry={nodes.Object_340.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_341.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.068, 3.717, 0.126]}
        rotation={[-Math.PI, -1.318, 1.589]}
        scale={[0.005, 0.03, 0.002]}
      >
        <mesh
          geometry={nodes.Object_343.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_344.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.047, 3.717, 0.1]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.005, 0.03, 0.002]}
      >
        <mesh
          geometry={nodes.Object_346.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_347.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.088, 3.717, 0.111]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.005, 0.03, 0.002]}
      >
        <mesh
          geometry={nodes.Object_349.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_350.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.073, 3.717, 0.085]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.005, 0.03, 0.002]}
      >
        <mesh
          geometry={nodes.Object_352.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_353.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.054, 3.748, 0.145]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.004, 0.026, 0.002]}
      >
        <mesh
          geometry={nodes.Object_359.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_360.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.071, 3.748, 0.15]}
        rotation={[-Math.PI, -1.318, 1.589]}
        scale={[0.004, 0.025, 0.002]}
      >
        <mesh
          geometry={nodes.Object_362.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_363.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.049, 3.748, 0.128]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.004, 0.025, 0.002]}
      >
        <mesh
          geometry={nodes.Object_365.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_366.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.084, 3.748, 0.138]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.004, 0.025, 0.002]}
      >
        <mesh
          geometry={nodes.Object_368.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_369.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.071, 3.748, 0.116]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.004, 0.025, 0.002]}
      >
        <mesh
          geometry={nodes.Object_371.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_372.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.066, 2.699, 0.525]}
        rotation={[0, -1.311, -1.553]}
        scale={[0.011, 0.06, 0.005]}
      >
        <mesh
          geometry={nodes.Object_386.geometry}
          material={materials.janelas}
        />
        <mesh
          geometry={nodes.Object_387.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.018, 2.608, 0.525]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_393.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_394.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_395.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[0.066, 2.608, 0.497]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_397.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_398.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_399.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[0.153, 2.608, 0.469]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_401.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_402.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_403.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.151, 2.608, 0.57]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_405.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_406.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_407.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.235, 2.608, 0.599]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_409.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_410.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_411.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.318, 2.608, 0.626]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_413.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_414.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_415.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.148, 2.534, 0.625]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_417.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_418.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_419.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.235, 2.532, 0.658]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_421.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_422.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_423.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.318, 2.53, 0.686]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_425.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_426.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_427.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[-0.018, 2.533, 0.584]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_429.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_430.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_431.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[0.066, 2.534, 0.559]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_433.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_434.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_435.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        position={[0.153, 2.534, 0.53]}
        rotation={[0, -1.234, -1.553]}
        scale={[0.016, 0.092, 0.009]}
      >
        <mesh
          geometry={nodes.Object_437.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_438.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_439.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group position={[0.563, 2.22, -0.028]} scale={0.182}>
        <mesh
          geometry={nodes.Object_441.geometry}
          material={materials["JANELAS.001"]}
        />
        <mesh
          geometry={nodes.Object_442.geometry}
          material={materials.JANELAS}
        />
        <mesh
          geometry={nodes.Object_443.geometry}
          material={materials.material_0}
        />
      </group>
      <group
        position={[-0.151, 2.421, -1.021]}
        rotation={[0, -0.584, 0]}
        scale={[0.24, 0.335, 0.24]}
      >
        <mesh
          geometry={nodes.Object_445.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_446.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.125, 2.703, -0.892]}
        rotation={[0, -1.269, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_450.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_451.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.249, 2.703, -0.932]}
        rotation={[-Math.PI, -0.733, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_453.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_454.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.023, 2.703, -0.981]}
        rotation={[0, -0.284, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_456.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_457.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.278, 2.703, -1.061]}
        rotation={[-Math.PI, 0.321, 1.589]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_459.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_460.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.107, 2.703, -1.146]}
        rotation={[0, 1.265, -1.553]}
        scale={[0.023, 0.185, 0.014]}
      >
        <mesh
          geometry={nodes.Object_462.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_463.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group position={[0.246, 2.261, 0.66]} scale={[0.113, 0.098, 0.111]}>
        <mesh
          geometry={nodes.Object_465.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_466.geometry}
          material={materials["LUZ.001"]}
        />
      </group>
      <group
        position={[-0.005, 2.869, -1.025]}
        rotation={[0, -0.685, -1.553]}
        scale={[0.008, 0.04, 0.003]}
      >
        <mesh
          geometry={nodes.Object_474.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_475.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[0.002, 2.869, -1.052]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.008, 0.038, 0.003]}
      >
        <mesh
          geometry={nodes.Object_477.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_478.geometry}
          material={materials.material}
        />
      </group>
      <group
        position={[-0.05, 2.869, -1.037]}
        rotation={[-Math.PI, -0.264, 1.589]}
        scale={[0.008, 0.038, 0.003]}
      >
        <mesh
          geometry={nodes.Object_480.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_481.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.03, 2.869, -1.07]}
        rotation={[-Math.PI, 1.292, 1.589]}
        scale={[0.008, 0.038, 0.003]}
      >
        <mesh
          geometry={nodes.Object_483.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_484.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group position={[-0.233, 2.745, -0.826]} scale={[0.038, 0.06, 0.038]}>
        <mesh
          geometry={nodes.Object_486.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Object_487.geometry}
          material={materials.VIDROS}
        />
      </group>
      <group
        position={[-0.213, 2.796, -0.832]}
        rotation={[0, 0.301, -1.553]}
        scale={[0.004, 0.03, 0.002]}
      >
        <mesh
          geometry={nodes.Object_491.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Object_492.geometry}
          material={materials.VIDROS}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["JANELAS.001"]}
        position={[0.409, 2.305, 0.335]}
        rotation={[-0.015, 0.401, 0.008]}
        scale={[0.231, 0.373, 0.231]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.material_0}
        position={[0.334, 2.261, 0.61]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.material_0}
        position={[0.309, 2.261, 0.616]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.material_0}
        position={[0.321, 2.278, 0.615]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials["JANELAS.001"]}
        position={[0.285, 2.24, 0.634]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["JANELAS.001"]}
        position={[0.287, 2.241, 0.63]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.material_0}
        position={[0.07, 2.266, 0.241]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.material_0}
        position={[0.094, 2.266, 0.233]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.material_0}
        position={[0.083, 2.284, 0.235]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials["JANELAS.001"]}
        position={[0.118, 2.245, 0.214]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials["JANELAS.001"]}
        position={[0.116, 2.246, 0.219]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.material_0}
        position={[0.137, 2.267, 0.21]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.material_0}
        position={[0.161, 2.267, 0.203]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.material_0}
        position={[0.149, 2.284, 0.204]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials["JANELAS.001"]}
        position={[0.185, 2.245, 0.183]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials["JANELAS.001"]}
        position={[0.183, 2.246, 0.188]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.material_0}
        position={[0.209, 2.267, 0.177]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.material_0}
        position={[0.234, 2.267, 0.169]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.material_0}
        position={[0.222, 2.284, 0.171]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials["JANELAS.001"]}
        position={[0.258, 2.246, 0.15]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials["JANELAS.001"]}
        position={[0.255, 2.246, 0.154]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.material_0}
        position={[0.277, 2.267, 0.148]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.material_0}
        position={[0.301, 2.267, 0.14]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.material_0}
        position={[0.29, 2.284, 0.142]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials["JANELAS.001"]}
        position={[0.325, 2.246, 0.121]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials["JANELAS.001"]}
        position={[0.323, 2.246, 0.125]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.material_0}
        position={[0.345, 2.267, 0.119]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.material_0}
        position={[0.369, 2.267, 0.111]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.material_0}
        position={[0.358, 2.284, 0.113]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials["JANELAS.001"]}
        position={[0.393, 2.245, 0.092]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials["JANELAS.001"]}
        position={[0.391, 2.246, 0.096]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.material_0}
        position={[0.412, 2.266, 0.088]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.material_0}
        position={[0.437, 2.266, 0.08]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.material_0}
        position={[0.425, 2.283, 0.082]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials["JANELAS.001"]}
        position={[0.461, 2.245, 0.061]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials["JANELAS.001"]}
        position={[0.458, 2.245, 0.066]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_76.geometry}
        material={materials.material_0}
        position={[0.48, 2.267, 0.056]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.material_0}
        position={[0.505, 2.267, 0.048]}
        rotation={[3.118, -0.258, 1.576]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials.material_0}
        position={[0.493, 2.284, 0.05]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials["JANELAS.001"]}
        position={[0.529, 2.245, 0.029]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials["JANELAS.001"]}
        position={[0.526, 2.246, 0.034]}
        rotation={[3.126, -0.363, -3.135]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.material_0}
        position={[0.536, 2.267, 0.057]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_88.geometry}
        material={materials.material_0}
        position={[0.544, 2.267, 0.082]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.material_0}
        position={[0.542, 2.284, 0.07]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials["JANELAS.001"]}
        position={[0.562, 2.246, 0.106]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials["JANELAS.001"]}
        position={[0.558, 2.246, 0.104]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.material_0}
        position={[0.567, 2.268, 0.13]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.material_0}
        position={[0.574, 2.268, 0.155]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.material_0}
        position={[0.573, 2.285, 0.143]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_102.geometry}
        material={materials["JANELAS.001"]}
        position={[0.593, 2.246, 0.179]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials["JANELAS.001"]}
        position={[0.589, 2.247, 0.176]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials.material_0}
        position={[0.597, 2.268, 0.2]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.material_0}
        position={[0.605, 2.268, 0.225]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.material_0}
        position={[0.603, 2.285, 0.213]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials["JANELAS.001"]}
        position={[0.624, 2.247, 0.249]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials["JANELAS.001"]}
        position={[0.619, 2.247, 0.247]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials.material_0}
        position={[0.628, 2.267, 0.27]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials.material_0}
        position={[0.635, 2.267, 0.294]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials.material_0}
        position={[0.633, 2.284, 0.283]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_122.geometry}
        material={materials["JANELAS.001"]}
        position={[0.654, 2.245, 0.318]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_124.geometry}
        material={materials["JANELAS.001"]}
        position={[0.649, 2.246, 0.316]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_126.geometry}
        material={materials.material_0}
        position={[0.657, 2.266, 0.341]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_128.geometry}
        material={materials.material_0}
        position={[0.665, 2.266, 0.365]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_130.geometry}
        material={materials.material_0}
        position={[0.663, 2.284, 0.354]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_132.geometry}
        material={materials["JANELAS.001"]}
        position={[0.684, 2.245, 0.389]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_134.geometry}
        material={materials["JANELAS.001"]}
        position={[0.679, 2.246, 0.387]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials.material_0}
        position={[0.689, 2.266, 0.41]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials.material_0}
        position={[0.696, 2.266, 0.435]}
        rotation={[3.047, 1.326, 1.674]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_140.geometry}
        material={materials.material_0}
        position={[0.695, 2.283, 0.423]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials["JANELAS.001"]}
        position={[0.715, 2.244, 0.459]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials["JANELAS.001"]}
        position={[0.711, 2.245, 0.457]}
        rotation={[3.098, 1.222, -3.088]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials["Material.002"]}
        position={[-0.593, 2.213, -0.554]}
        scale={0.349}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials["Material.005"]}
        position={[-0.593, 2.213, -0.554]}
        scale={0.349}
      />
      <mesh
        geometry={nodes.Object_153.geometry}
        material={materials["JANELAS.001"]}
        position={[0.636, 2.244, 0.49]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_155.geometry}
        material={materials["JANELAS.001"]}
        position={[0.638, 2.244, 0.485]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_157.geometry}
        material={materials.material_0}
        position={[0.615, 2.264, 0.496]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_159.geometry}
        material={materials.material_0}
        position={[0.591, 2.264, 0.502]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_161.geometry}
        material={materials.material_0}
        position={[0.602, 2.281, 0.501]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_163.geometry}
        material={materials["JANELAS.001"]}
        position={[0.566, 2.243, 0.52]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_165.geometry}
        material={materials["JANELAS.001"]}
        position={[0.568, 2.243, 0.516]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_167.geometry}
        material={materials["JANELAS.001"]}
        position={[0.546, 2.264, 0.525]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_169.geometry}
        material={materials.material_0}
        position={[0.521, 2.264, 0.531]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_171.geometry}
        material={materials.material_0}
        position={[0.532, 2.281, 0.53]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_173.geometry}
        material={materials["JANELAS.001"]}
        position={[0.496, 2.243, 0.549]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_175.geometry}
        material={materials["JANELAS.001"]}
        position={[0.498, 2.243, 0.545]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_177.geometry}
        material={materials.material_0}
        position={[0.477, 2.262, 0.554]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_179.geometry}
        material={materials.material_0}
        position={[0.452, 2.262, 0.56]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_181.geometry}
        material={materials.material_0}
        position={[0.463, 2.28, 0.559]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_183.geometry}
        material={materials["JANELAS.001"]}
        position={[0.427, 2.241, 0.578]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_185.geometry}
        material={materials["JANELAS.001"]}
        position={[0.429, 2.242, 0.574]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_187.geometry}
        material={materials.material_0}
        position={[0.404, 2.261, 0.582]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_189.geometry}
        material={materials.material_0}
        position={[0.38, 2.261, 0.588]}
        rotation={[0.023, 0.206, -1.564]}
        scale={[0.009, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_191.geometry}
        material={materials.material_0}
        position={[0.391, 2.278, 0.587]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.006, 0.002, 0.002]}
      />
      <mesh
        geometry={nodes.Object_193.geometry}
        material={materials["JANELAS.001"]}
        position={[0.355, 2.24, 0.606]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.007, 0.009, 0.009]}
      />
      <mesh
        geometry={nodes.Object_195.geometry}
        material={materials["JANELAS.001"]}
        position={[0.357, 2.24, 0.602]}
        rotation={[0.016, 0.31, 0.008]}
        scale={[0.003, 0.009, 0.006]}
      />
      <mesh
        geometry={nodes.Object_197.geometry}
        material={materials["Material.013"]}
        position={[0.203, 2.43, 0.393]}
        rotation={[1.603, 0.032, -1.931]}
        scale={[0.013, 0.012, 0.001]}
      />
      <mesh
        geometry={nodes.Object_199.geometry}
        material={materials["Material.012"]}
        position={[0.206, 2.444, 0.404]}
        rotation={[0.011, 0.313, -1.582]}
        scale={[0.013, 0.012, 0.001]}
      />
      <mesh
        geometry={nodes.Object_267.geometry}
        material={materials["JANELAS.001"]}
        position={[0.727, 2.216, -0.909]}
        scale={0.182}
      />
      <mesh
        geometry={nodes.Object_275.geometry}
        material={materials["Material.007"]}
        position={[-0.085, 2.216, -0.081]}
        scale={[0.24, 0.335, 0.24]}
      />
      <mesh
        geometry={nodes.Object_277.geometry}
        material={materials["Material.002"]}
        position={[-0.085, 2.216, -0.081]}
        scale={[0.24, 0.335, 0.24]}
      />
      <mesh
        geometry={nodes.Object_298.geometry}
        material={materials.material_0}
        position={[-0.855, 2.216, -0.081]}
        scale={[0.24, 0.335, 0.24]}
      />
      <mesh
        geometry={nodes.Object_300.geometry}
        material={materials["Material.002"]}
        position={[-0.855, 2.216, -0.081]}
        scale={[0.24, 0.335, 0.24]}
      />
      <mesh
        geometry={nodes.Object_317.geometry}
        material={materials["Material.005"]}
        position={[-0.308, 3.536, 0.251]}
        scale={[0.046, 0.09, 0.046]}
      />
      <mesh
        geometry={nodes.Object_319.geometry}
        material={materials["Material.007"]}
        position={[-0.308, 3.536, 0.251]}
        scale={[0.046, 0.09, 0.046]}
      />
      <mesh
        geometry={nodes.Object_336.geometry}
        material={materials["Material.005"]}
        position={[-0.265, 3.609, 0.254]}
        scale={[0.038, 0.074, 0.038]}
      />
      <mesh
        geometry={nodes.Object_338.geometry}
        material={materials["Material.007"]}
        position={[-0.265, 3.609, 0.254]}
        scale={[0.038, 0.074, 0.038]}
      />
      <mesh
        geometry={nodes.Object_355.geometry}
        material={materials["Material.005"]}
        position={[-0.232, 3.658, 0.257]}
        scale={[0.032, 0.062, 0.032]}
      />
      <mesh
        geometry={nodes.Object_357.geometry}
        material={materials["Material.007"]}
        position={[-0.232, 3.658, 0.257]}
        scale={[0.032, 0.062, 0.032]}
      />
      <mesh
        geometry={nodes.Object_374.geometry}
        material={materials["Material.005"]}
        position={[0.141, 2.526, 0.479]}
        scale={[0.03, 0.057, 0.027]}
      />
      <mesh
        geometry={nodes.Object_376.geometry}
        material={materials["Material.002"]}
        position={[0.141, 2.526, 0.479]}
        scale={[0.03, 0.057, 0.027]}
      />
      <mesh
        geometry={nodes.Object_378.geometry}
        material={materials["Material.005"]}
        position={[0.234, 2.649, 0.397]}
        scale={[0.036, 0.096, 0.032]}
      />
      <mesh
        geometry={nodes.Object_380.geometry}
        material={materials["Material.002"]}
        position={[0.234, 2.786, 0.397]}
        scale={[0.036, 0.096, 0.032]}
      />
      <mesh
        geometry={nodes.Object_382.geometry}
        material={materials["Material.005"]}
        position={[-0.071, 2.631, 0.502]}
        scale={[0.043, 0.083, 0.042]}
      />
      <mesh
        geometry={nodes.Object_384.geometry}
        material={materials["Material.002"]}
        position={[-0.071, 2.81, 0.502]}
        scale={[0.043, 0.189, 0.042]}
      />
      <mesh
        geometry={nodes.Object_389.geometry}
        material={materials["Material.005"]}
        position={[-0.382, 2.644, 0.608]}
        scale={[0.036, 0.083, 0.032]}
      />
      <mesh
        geometry={nodes.Object_391.geometry}
        material={materials["Material.002"]}
        position={[-0.382, 2.763, 0.608]}
        scale={[0.036, 0.083, 0.032]}
      />
      <mesh
        geometry={nodes.Object_448.geometry}
        material={materials["Material.002"]}
        position={[-0.151, 3.137, -1.021]}
        rotation={[0, -0.584, 0]}
        scale={[0.24, 0.707, 0.24]}
      />
      <mesh
        geometry={nodes.Object_468.geometry}
        material={materials["Material.007"]}
        position={[0.246, 2.4, 0.66]}
        scale={[0.113, 0.098, 0.111]}
      />
      <mesh
        geometry={nodes.Object_470.geometry}
        material={materials["Material.005"]}
        position={[-0.024, 2.772, -1.044]}
        scale={[0.049, 0.115, 0.049]}
      />
      <mesh
        geometry={nodes.Object_472.geometry}
        material={materials["Material.007"]}
        position={[-0.024, 2.936, -1.044]}
        scale={[0.049, 0.115, 0.049]}
      />
      <mesh
        geometry={nodes.Object_489.geometry}
        material={materials["Material.007"]}
        position={[-0.233, 2.84, -0.826]}
        scale={[0.038, 0.075, 0.038]}
      />
      <mesh
        geometry={nodes.Object_494.geometry}
        material={materials.JANELAS}
        position={[-0.231, 2.73, -0.442]}
        scale={[0.011, 0.021, 0.013]}
      />
    </group>
  );
}

useGLTF.preload("assets/hogwarts_3d/scene.gltf");
