/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Gustavo.Fabi (https://sketchfab.com/Gustavo.Fabi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/musical-notes-8e1f180f69a84941921bd8b90d424e23
Title: Musical Notes
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Note1({ position, rotation }) {
  const { nodes, materials } = useGLTF("assets/musical_notes/scene.gltf");
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.SM_MusicNote_03_lambert1_0.geometry}
        material={materials.lambert1}
        position={position}
        rotation={rotation}
      />
    </group>
  );
}
export function Note2({ position, rotation }) {
  const { nodes, materials } = useGLTF("assets/musical_notes/scene.gltf");
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.SM_MusicNote_02_lambert2_0.geometry}
        material={materials.lambert2}
        position={position}
        rotation={rotation}
        scale={2.532}
      />
    </group>
  );
}
export function Note3({ position, rotation = [0, 0, 0] }) {
  const { nodes, materials } = useGLTF("assets/musical_notes/scene.gltf");
  return (
    <group dispose={null}>
      <mesh
        geometry={nodes.SM_MusicNote_01_lambert3_0.geometry}
        material={materials.lambert3}
        position={position}
        rotatio={rotation}
        scale={1.514}
      />
    </group>
  );
}

useGLTF.preload("assets/musical_notes/scene.gltf");
